### ISSUE TITLE
Feature request: enabling affinity rules for fluentds

### ISSUE THREAD

**Issue by m-yosefpor** [openshift/cluster-logging-operator#1105]
Right now it is possible to define a nodeSelector for fluentd daemonSets via `.spec.collection.logs.fluentd.nodeSelector` in `ClusterLogging`, however, more complex affinity rules such as the following is not currently possible:

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
```

P.S.1: This can be also added to other components (es, kibana, .. ) as well.
P.S.2: I'm willing to contribute a PR for this if the feature matches the project guidelines.
