### ISSUE TITLE
Eliminate the Promtheus operator dependency of the "arbitraryFSAccessThroughSMs"

### ISSUE THREAD

**Issue by bysnupy** [openshift/cluster-logging-operator#1106]
**Describe the bug**
Use the service serving CA in generated service serving secret instead of the CA cert on the Prometheus Operator local container filesystem.

* Description on issues:
Currently, Cluster Logging Operator assumes only running with Prometheus Operator in "openshift-monitoring", not "openshift-user-workload-monitoring" one.
However Cluster Logging Operator(EFK) is a user worload treatment on ROSA, and also not providing `openshift.io/cluster-monitoring: "true"` label in "openshift-logging".
The user workload Prometheues Operator in "openshift-user-workload-monitoring" does not allow to access the prometheus local FS,
as a result "fluentd" ServiceMonitor with "/etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt" always is failed to access.\

// cluster monitoring prometheus allow to access own local fs.
```console
$ oc get prometheus k8s -o yaml -n openshift-monitoring
:
  arbitraryFSAccessThroughSMs: {}
```
// In contrast, user workload monitoring prometheus does not allow to access own local fs.
```console
$ oc get prometheus user-workload -o yaml -n openshift-user-workload-monitoring
:
  arbitraryFSAccessThroughSMs:
    deny: true
```

It causes incorrect alert notification as follows,

  https://issues.redhat.com/browse/LOG-1561

And service serving cert is consist of CA and server cert together basically[0],
I think we can get the same CA from generated service serving cert secret, "/etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt" is duplicated with that.
Additionally getting CA cert from local fs is not secure than extracting the CA cert through secret and it depends on external prometheus CA cert too.

As a result, the following config would work well to communicate with any prometheus operator.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluentd
  namespace: openshift-logging
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: tls.crt
          name: fluentd-metrics
      serverName: fluentd.openshift-logging.svc
  jobLabel: monitor-fluentd
  namespaceSelector:
    matchNames:
    - openshift-logging
  selector:
    matchLabels:
      logging-infra: support
```
[0] including the CA of the service serving certificate and its server cert together as follows.
https://github.com/openshift/library-go/blob/70a39c8ba7a12c5903391c0a3ae7849c0fb4af73/pkg/crypto/crypto.go#L755-L758
~~~
server := &TLSCertificateConfig{
  Certs: append([]*x509.Certificate{serverCrt}, ca.Config.Certs...),
  Key:   serverPrivateKey,
}
~~~

**Environment**
- ROSA (v4.7.z)
- ClusterLogging instance

**Logs**
~~~
level=warn ts=2021-07-02T02:39:00.701373761Z caller=operator.go:1675 component=prometheusoperator msg="skipping servicemonitor" error="it accesses file system via tls config which Prometheus specification prohibits" servicemonitor=openshift-logging/fluentd namespace=openshift-user-workload-monitoring prometheus=user-workload
~~~

**Expected behavior**
The Prometheus operator in "openshift-user-workload-monitoring" can communicate with "fluentd" target through ServiceMonitor.

**Actual behavior**
Evaluated the invalid servicemonitor TLSconfig and firing incorrect alert.

**To Reproduce**
After removing  `openshift.io/cluster-monitoring: "true"` label from "openshift-logging", install cluster logging operator(EFK).
Then you can reproduce this issue as always.

**Additional context**
