### ISSUE TITLE
Feature request: Enable podTemplate for elasticsearch

### ISSUE THREAD

**Issue by YiannisGkoufas** [openshift/cluster-logging-operator#1132]
Hi all, I am hitting this issue: https://access.redhat.com/solutions/5195611
Basically I need to be able to add this configuration:
```yaml
podTemplate:
  metadata:
    labels:
      tuned.openshift.io/elasticsearch: ""
```
on the `elastricsearch` part of the spec of `ClusterLogging` but I don't think it's supported.
Let me know if the functionality is there and I am missing something.
