### ISSUE TITLE
ClusterLogForwarder not able to use multiple Elasticsearch nodes as outputs

### ISSUE THREAD

**Issue by theodor2311** [openshift/cluster-logging-operator#1238]
**Describe the bug**
The ClusterLogForwarder using Elasticsearch as outputs is not able to configure multiple Elasticsearch nodes in the same Elasticsearch cluster.

**Environment**
- OpenShift 4.8.15
- cluster-logging.5.2.2-21

**Rationale**
The deployment of the Elasticsearch cluster does not include any load balancer/VIP in the architecture, the normal practice is to pass a list of Elasticsearch nodes to do the load balancing at the client-side. E.g Kibana using "elasticsearch.hosts", Fluentd using "hosts".

**To Reproduce**
1. Create a ClusterLogForwarder with a list of Elasticsearch.
```yaml
apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
   - name: elasticsearch-insecure
     type: "elasticsearch"
     url: http://elasticsearch.insecure.com:9200,http://elasticsearch2.insecure.com:9200
  pipelines:
   ...
```
2. Check the /etc/fluent/fluent.conf from the fluentd pods.

**Expected behavior**
The operator is able to parse the spec.outputs.url to "hosts" if using Elasticsearch as outputs.
```
...
<match **>
  @type copy
  <store>
    @type elasticsearch
    @id elasticsearch_insecure
    hosts http://elasticsearch.insecure.com:9200,http://elasticsearch2.insecure.com:9200
...
```

**Actual behavior**
The operator will parse the spec.outputs.url, tweak it, and put it to the "host" configuration.
```
...
<match **>
  @type copy
  <store>
    @type elasticsearch
    @id elasticsearch_insecure
    host elasticsearch.insecure.com:9200,http
    port 9200
...
```

**Additional context**
Kibana using "elasticsearch.hosts":
https://www.elastic.co/guide/en/kibana/current/production.html#high-availability
Fluentd using "hosts":
https://docs.fluentd.org/output/elasticsearch#hosts-optional
