### ISSUE TITLE
Failure creating Elasticsearch CR

### ISSUE THREAD

**Issue by cmoulliard** [openshift/cluster-logging-operator#151]
### Issue

Cluster logging can't be deployed on ocp4. The `Cluster Logging Operator` reports this error

```
time="2019-04-09T16:14:18Z" level=error msg="error syncing key (openshift-logging/instance): Unable to create or update logstore for \"instance\": Failure creating Elasticsearch CR: failed to get resource client: failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(logging.openshift.io/v1, Kind=Elasticsearch): no matches for kind \"Elasticsearch\" in version \"logging.openshift.io/v1\""
time="2019-04-09T16:14:23Z" level=error msg="error syncing key (openshift-logging/instance): Unable to create or update logstore for \"instance\": Failure creating Elasticsearch CR: failed to get resource client: failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(logging.openshift.io/v1, Kind=Elasticsearch): no matches for kind \"Elasticsearch\" in version \"logging.openshift.io/v1\""
```

after we have applied the following `CR` on the namespace `openshift-logging`

```
oc create -n openshift-logging -f hack/cr.yaml
where cr.yaml

apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      storage: {}
      redundancyPolicy: "ZeroRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  curation:
    type: "curator"
    curator:
      schedule: "30 3,9,15,21 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
-->
clusterlogging.logging.openshift.io/instance created
```

### Info

```
Red Hat OpenShift Container Platform
OpenShift is Red Hat's container application platform that allows developers to quickly develop, host, and scale applications in a cloud environment.

Cluster ID
a3acddcb-6eff-41d5-b10c-eafb2b905d11
Kubernetes Master Version
v1.12.4+0ba401e

Cluster Logging Operator deployed : 4.1.0 (preview)
```
