### ISSUE TITLE
Wrong indentation for the field - metadata  within hack/cr-aws.yaml

### ISSUE THREAD

**Issue by cmoulliard** [openshift/cluster-logging-operator#152]
### Issue

The `METADATA` field is not well positioned within the file `hack/cr-aws.yaml`

```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
  metadata:
  name: "instance"
```

Should be

```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
```
