### ISSUE TITLE
Labels with special characters (".", "/") are not supported by Loki labelKeys

### ISSUE THREAD

**Issue by bo0ts** [openshift/cluster-logging-operator#1790]
**Describe the bug**

We use a `ClusterLogForwarder` to Loki with custom labels. The labels keys contain slashes and dots.

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: our-loki
      type: "loki"
      url: ...
      secret:
        name: ...
      loki:
        labelKeys:
        - kubernetes.labels.ourname.com/service-name
        - kubernetes.namespace_labels.ourname.com/center
  pipelines:
    - name: all-logs
      detectMultilineErrors: true
      inputRefs:
        - application
      outputRefs:
        - our-loki
```

Those labels do not end up in our loki instance. A look at the generated collector config explains why:

```
<label @CENTRAL_LOKI>
  <filter **>
    @type record_modifier
    <record>
      _kubernetes_namespace_labels_ourname_com/center ${record.dig("kubernetes","namespace_labels","ourname","com/center")}
      _kubernetes_namespace_name ${record.dig("kubernetes","namespace_name")}
    </record>
  </filter>

  <match **>
    @type loki
    @id central_loki
    line_format json
    ... 
    <label>
      kubernetes_labels_ourname_com/service-name _kubernetes_labels_ourname_com/service-name
      kubernetes_namespace_labels_ourname_com/center _kubernetes_namespace_labels_ourname_com/center
    </label>
    <buffer>
    ...
    </buffer>
  </match>
</label>
```

The resulting label is not valid in Loki (contains a slash) and the way the record is accessed is wrong as well. We could not get this to work using escapes.

**Environment**
- OpenShift 4.9
- Cluster Logging 5.5.5
- Loki 2.7

**Expected behavior**

Provide a way to specify labels with special characters as they are supported and used by k8s.
