### ISSUE TITLE
ClusterLogForwarder missing indexKey property for Splunk

### ISSUE THREAD

**Issue by sedadas** [openshift/cluster-logging-operator#2882]
**Describe the bug**
Previously, it was possible to configure an index key for splunk which would reference a metadata key for the name of the index like this:

```yaml
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  inputs:
    - name: application-filtered-logs
      application:
        selector:
          matchLabels:
            foo: bar
  pipelines:
    - inputRefs:
        - application-filtered-logs
      name: splunk-forwarder
      outputRefs:
        - splunk-receiver
  outputs:
    - name: splunk-receiver
      secret:
        name: vector-splunk-secret
      type: splunk
      url: "somesplunkurl.example.com"
      splunk:
        indexKey: kubernetes.labels.splunkindex
```

If this key was not available, the operator would forward the logs to `default-index`. In version 6.0 of logging, this is not possible

**Environment**
- OpenShift 4.16.16
- Logging 6.0.2

Is this change deliberate? If so, how can I replicate this functionality with the new version of the operator?

**Logs**
N/A

**Expected behavior**
I expected to be able to forward logs based on a label.

**Actual behavior**
The property is dropped from the CRD and validation fails when creating a new CR with this property.

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove old `ClusterLogForwarder` with the `indexKey` configuration
2. Remove version 5.9 of logging operator
3. Install version 6.0.2 of logging operator
4. Adapt old `ClusterLogForwarder` to the new CRD, leave `indexKey` in
5. Get error when attempting to create the `ClusterLogForwarder`
6. Remove `indexKey`, creation works

**Additional context**
N/A
