### ISSUE TITLE
"add" filters to inject fields in log records

### ISSUE THREAD

**Issue by bprieur** [openshift/cluster-logging-operator#2885]
**Environment**: openshift 4.16
**Operator channel**: 6.x

Like _prune_ filter to delete some fields, it should be great having a filter to inject fields in log records.

Or maybe this feature is out of scope of this operator and aggregators are needed between collectors and receivers?

Some example :

```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
# ...
spec:
  filters:
    - name: <filter_name>
      type: add
      add:
        # <key>: <value>
        tag: "openshift.app.{.kubernetes.pod_name||default}"
```

```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
# ...
spec:
  filters:
    - name: <filter_name>
      type: add_pattern
      from:
        - key: kubernetes.namespace_name
          ref: myref
          pattern: ^(.+)-(.+)-(.+)$
      add:
        # <key>: <value>
        tag: "openshift.app.$myref[1]"
```
