### ISSUE TITLE
steps to be followed in output spec to use IAM role for sts enabled clusters

### ISSUE THREAD

**Issue by sankalp-7** [openshift/cluster-logging-operator#2942]
**Issue with STS Token Configuration in CloudWatch Output Spec**
I am following the OpenShift documentation for configuring log forwarding to CloudWatch for STS-enabled clusters:
[OpenShift Log Forwarding Documentation](https://docs.openshift.com/rosa/observability/logging/log_collection_forwarding/configuring-log-forwarding.html#rosa-cluster-logging-collector-log-forward-sts-cloudwatch_configuring-log-forwarding).

Current Configuration
The document specifies the following Secret for STS authentication:

```
apiVersion: v1
kind: Secret
metadata:
  name: instance
  namespace: openshift-logging
stringData:
  credentials: |-
    [default]
    sts_regional_endpoints = regional
    role_arn: <role_ARN>  
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
```

This approach works for apiVersion: logging.openshift.io/v1, but I am using apiVersion: observability.openshift.io/v1, where the output spec requires a different configuration.

I have configured the CloudWatch output spec as follows:

```
outputs:
  - cloudwatch:
      authentication:
        iamRole:
          roleARN:
            key: credentials
            secretName: instance
          token:
            from: secret
            secret:
              key: credentials
              name: instance
    type: cloudwatch
```
However, I am encountering an error:

`[Invalid JWT token for STS](error: InvalidIdentityTokenException: The ID Token provided is not a valid JWT.)`

Additional Details
The service account associated with the forwarder is correctly annotated with the IAM role ARN.
The IAM role in AWS has the correct trust relationship to allow STS-based authentication.

Request for Assistance
What is the correct way to configure the output spec for CloudWatch when using the Secret mentioned in the documentation? especially for the token part of the spec

Is there an alternative approach to enable STS authentication for log forwarding in apiVersion: observability.openshift.io/v1?
Would appreciate any guidance on resolving this issue.

@jcantrill @vimalk78 @Clee2691
