### ISSUE TITLE
ElasticSearch or Cluster-Logging Operator should extend the vm.max_map_count

### ISSUE THREAD

**Issue by jparrill** [openshift/cluster-logging-operator#336]
The kernel parameter regarding `vm.max_map_count` should be modified by Cluster-Logging-Operator or ElasticSearch Operator in order to allow deploy ElasticSearch instance correctly into the concrete project.

```
# Should be vm.max_map_count=262144
sysctl -n vm.max_map_count                          
65530
```

- MC Patch
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-sysctl-elastic
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          # vm.max_map_count=262144
          source: data:text/plain;charset=utf-8;base64,dm0ubWF4X21hcF9jb3VudD0yNjIxNDQ=
        filesystem: root
        mode: 0644
        path: /etc/sysctl.d/99-elasticsearch.conf
```
