### ISSUE TITLE
how to set MERGE_JSON_LOG for fluentd

### ISSUE THREAD

**Issue by nickma82** [openshift/cluster-logging-operator#377]
Hi,
I'm trying to set the `MERGE_JSON_LOG=true` while preserving the `ManagementState==Manage` (unlike [the solution from the **docs**](https://github.com/openshift/cluster-logging-operator/blob/master/docs/unmanaged_configuration.md)).

**Target**  (DaemonSet autogenerated by the cluster-logging-operator)
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: fluentd
spec:
  template:
    spec:
      containers:
        - resources:
          name: fluentd
          env:
            - name: MERGE_JSON_LOG
              value: 'true'
```
**Current State**
I've got a `clusterlogging.4.3.1` operator up and running and every (manual) manipulation in the DaemonSet is instantly reverted.
[generators/forwarding/fluentd/templates.go#L167](https://github.com/openshift/cluster-logging-operator/blob/release-4.3/pkg/generators/forwarding/fluentd/templates.go#L167) looks like what I wanted to do, but I cant figure out how to pass the `json_fields`/`ENV` correctly.

My `CL-instance.yaml` looks like this:
```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  collection:
    logs:
      type: fluentd
      fluentd:
        merge_json_log: true          # <----  that's what I'd like to do
```

Any hint appreciated!
Best, Nick
