### ISSUE TITLE
ImageStreams are not propagated to the deployment

### ISSUE THREAD

**Issue by jcantrill** [openshift/cluster-logging-operator#54]
There looks to be an issue with whats in the manifest:
https://github.com/openshift/cluster-logging-operator/blob/master/manifests/05-deployment.yaml#L29-L42

and what gets rolled out.
```
    spec:
      containers:
      - command:
        - cluster-logging-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: cluster-logging-operator
        - name: ELASTICSEARCH_IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev:v4.0.0-0.93.0.0-ose-elasticsearch-operator
        image: quay.io/openshift/cluster-logging-operator:latest
        imagePullPolicy: IfNotPresent

```
Note `ELASTICSEARCH_IMAGE` I manually added to try and update the ES image.  It didnt exist before that.
This will inhibit us from deploying the correct images during release

Also, it doesn't appear the value was added to the ES operator deployment:
```
  - command:
    - elasticsearch-operator
    env:
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OPERATOR_NAME
      value: elasticsearch-operator
    image: quay.io/openshift/elasticsearch-operator:latest

```
