### ISSUE TITLE
Reconsider how collector nodeSelector is defined

### ISSUE THREAD

**Issue by jcantrill** [openshift/cluster-logging-operator#58]
The recent submission of a PR to support rsyslog has made me question why we have not taken the opportunity in 4.0 to possibly change our node selector for the collector. Consider the following;
Ref: https://github.com/openshift/cluster-logging-operator/blob/master/hack/cr.yaml
```
...
  collection:
    logCollection:
      type: "fluentd"
      fluentd:
        nodeSelector:
          logging-infra-fluentd: "true"
      rsyslog:
        nodeSelector:
          logging-infra-rsyslog: "true"
```
Wouldn't it be more reasonable to have a single label which takes a collector:
```
logging-infra-collector: "fluentd | rsyslog"
```
Additionally,  moving to a 'well-known-label'='known value' pattern would allow us to remove the nodeselector block all together.  I do not see a need for a customer to have to modify the selector

Either way allows us to split collectors across nodes, but the later would allow us to add additional collectors without requiring an additional label.   
* Why did we decide to continue to use a boolean to identify which nodes will receive the collector?  
* Additionally, node labeling is now outside the responsibility of this operator correct?  What is the workflow to get alternate collectors landed on nodes?
* One could additionally argue that `eventrouter` is a specialized collector. Is there a need to support a variant of landing multiple collectors on the same node?
