### ISSUE TITLE
Character corruption when sending audit log to syslog server by LogForwarding API

### ISSUE THREAD

**Issue by mosuke5** [openshift/cluster-logging-operator#642]
Hello.
I tried to send kubernetes audit log to Cluster Logging ElasticSearch by LogForwarding API. (OpenShift 4.4) It worked but character corruption happened.
Do you have any solution or root cause?

```
Aug  3 09:48:29 ec2-18-136-128-120.ap-southeast-1.compute.amazonaws.com Y^H�#000#025�kind�Event�apiVersion�audit.k8s.io/v1�level�Metadata�auditID�$521ddb61-d1e9-4f98-b7cc-6560fd8137db�stage�ResponseComplete�requestURI�,/api/v1/namespaces/openshift-logging/secrets�verb�create�user��username�@system: serviceaccount:openshift-logging:cluster-logging-operator�uid�$43965a51-5ce9-46b8-b530-9d385589c23d�groups��system:serviceaccounts�(system:serviceaccounts:openshift-logging�system:authenticated�sourceIPs��10.0.164.6�userAgent�@cluster-logging-operator/v0.0.0 (linux/amd64) kubernetes/$Format�objectRef��resource�secrets�namespace�openshift-logging�name�fluentd�apiVersion�v1�responseStatus��status�Failure�reason�AlreadyExists�code�#001��requestReceivedTimestamp�2020-08-03T09:48:28.173629Z�stageTimestamp�2020-08-03T09:48:28.183832Z�annotations��authorization.k8s.io/decision�allow�authorization.k8s.io/reason��RBAC:
```

My LogForwarding setting is here.

```
apiVersion: "logging.openshift.io/v1alpha1"
kind: "LogForwarding"
metadata:
  name: instance
  namespace: openshift-logging
spec:
  disableDefaultForwarding: true
  outputs:
   - name: elasticsearch
     type: "elasticsearch"
     endpoint: elasticsearch.openshift-logging.svc:9200
     secret:
        name: fluentd
  - name: syslog
     type: "forward"
     endpoint: my-syslog-server:514
  pipelines:
   - name: container-logs
     inputSource: logs.app
     outputRefs:
     - elasticsearch
   - name: infra-logs
     inputSource: logs.infra
     outputRefs:
     - elasticsearch
   - name: audit-logs
     inputSource: logs.audit
     outputRefs:
     - elasticsearch
     - syslog
```
