### ISSUE TITLE
LogCollector: Valid fluentd.conf gets replaced by an invalid fluentd.conf

### ISSUE THREAD

**Issue by JoaoBraveCoding** [openshift/cluster-logging-operator#804]
**Describe the bug**
Deployed `cluster-logging-operator` together with two CRs a `ClusterLogging` and a `ClusterLogForwarder`. These CRs are configured in such a way as to only deploy the fluentd DaemonSet to collect logs and then forward them to an in cluster fluentd instance that will process them (aggregator). I can see that the operator deploys the DaemonSet and all pods get created fine, the problem is that then no logs arrive at the aggregator. Looked into the problem and found out that the operator when processing the CRDs will generate a valid `fluentd` ConfigMap from where the DaemonSet pods will take their configuration, but after a few reconciles the operator will update this ConfigMap to have `fluentd.conf: ""` making it invalid and breaking the log collection.

**Environment**
- Versions of OpenShift, Cluster Logging  and any other relevant components

okd-release:4.5.0-0.okd-2020-10-15-235428

fedora-coreos-32.20201004.3.0-openstack.x86_64

- ClusterLogging instance

quay.io/openshift/origin-cluster-logging-operator:4.6

**Logs**

https://gist.github.com/JoaoBraveCoding/a3957c06fb26b2772837d7f55fdd8444

**Expected behavior**

I would expect the operator to consume both CRs, generate the proper `fluentd.conf` as it does and then only update it if I were to update the CRs

**Actual behavior**
Operator generates the proper configuration but a few seconds after it replaces it by `fluentd.conf: ""` and never again generates the proper configuration unless I delete the `fluentd` ConfigMap and delete the operator pod.

**To Reproduce**
1. Deploy the cluster-logging-operator.
2. Deploy the CR `ClusterLogging` like:

```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  annotations:
    clusterlogging.openshift.io/logforwardingtechpreview: enabled
  name: instance
spec:
  collection:
    logs:
      fluentd:
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      type: fluentd
  managementState: Managed
```

3. Deploy the CR `ClusterLogForwarder` like:

```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
spec:
  outputs:
  - name: fluentd-forward
    type: fluentdForward
    url: tcp://fluentd-aggregator.openshift-logging.svc:24224
  pipelines:
  - inputRefs:
    - application
    - infrastructure
    - audit
    name: forward-to-fluentd-central-monitoring
    outputRefs:
    - fluentd-forward
```

4. Check the cluster-logging-operator logs, they should be similar to the ones I've posted previously in the issue. You can also check that `fluentd.conf: ""` in the ConfigMap `fluentd`.

**Additional context**

You can check what happens to the ConfigMap by running something like:

```bash
while [ true ]; do oc get cm fluentd -w -o yaml --export >> out.txt; done
```
