### ISSUE TITLE
OCP 4.5.19, After configuring logforwarding , not seeing any logs in Kibana 

### ISSUE THREAD

**Issue by MastanaGuru** [openshift/cluster-logging-operator#832]
**Describe the bug**
We are upgrading from 3.11 to OCP 4.5.19. But after configuring LogForwarding instance to forward logs to default internal Elasticsearch log store, not seeing any logs in Kibana. Tried with both elasticsearch and fluentd secret.

```
oc annotate clusterlogging.logging.openshift.io/instance clusterlogging.openshift.io/logforwardingtechpreview=enabled --overwrite=true
```

```
- apiVersion: logging.openshift.io/v1alpha1
  kind: LogForwarding
  metadata:
    namespace: openshift-logging
    name: instance
  spec:
    disableDefaultForwarding: true
    # disableDefaultForwarding: false
    outputs:
      - name: clo-default-output-es
        type: elasticsearch
        endpoint: 'elasticsearch.openshift-logging.svc:9200'
        secret:
          # name: elasticsearch
          name: fluentd
    pipelines:
      - name: clo-default-app-pipeline
        inputSource: logs.app
        outputRefs:
          - clo-default-output-es
      - name: clo-default-infra-pipeline
        inputSource: logs.infra
        outputRefs:
          - clo-default-output-es
      - name: clo-default-audit-pipeline
        inputSource: logs.audit
        outputRefs:
          - clo-default-output-es
```
