### ISSUE TITLE
Config for `storageClassName` defaults to `emptyDir` instead of the default class

### ISSUE THREAD

**Issue by 4n4nd** [openshift/cluster-logging-operator#869]
**Describe the bug**
In the `ClusterLogging` CR when storage is not specified for elasticsearch, it defaults to ephemeral storage (`emptyDir`) which might result in loss of logs.

Example config:
```yaml
---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 1d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
    elasticsearch:
      nodeCount: 3
      storage:
        size: 200G
      redundancyPolicy: "ZeroRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  curation:
    type: "curator"
    curator:
      schedule: "30 3 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
```

**Environment**
- Openshift Version: 4.5.17
- ClusterLogging installed from channel 4.5

**Logs**
N/A

**Expected behavior**
By default it should use the default storageClass set for the cluster instead of using `emptyDir`

**Actual behavior**
Uses ephemeral storage by default

**To Reproduce**
1.  Install CLO channel 4.5
2.  Use the above example CR from description
3.  Check elasticsearch deployments for storage types used

**Additional context**
N/A
